name: Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check jsonwebtoken/ spec/

  spec:
    strategy:
      matrix:
        lua: ["5.3", "5.4", "5.5"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: ${{ matrix.lua }}
      - uses: leafo/gh-actions-luarocks@v5
        with:
          luarocksVersion: "3.13.0"
      - run: luarocks install busted
      - run: busted

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-lua@v13
        with:
          luaVersion: "5.4"
      - uses: leafo/gh-actions-luarocks@v5
        with:
          luarocksVersion: "3.13.0"
      - run: luarocks install luacheck
      - run: luacheck jsonwebtoken spec
